# OpenOS Seed System
#
# This is the minimal "bootloader" that gets installed from the USB stick.
# It provides:
#   - GRUB boot menu (recovery)
#   - Networking (DHCP + Tailscale)
#   - A lightweight HTTP server with the setup wizard
#   - The ability to pull a full OpenOS version from GitHub
#
# The seed is intentionally tiny: no PostgreSQL, no Nginx, no apps.
# Those come with the full version that the seed pulls.
{ config, lib, pkgs, ... }:
let
  # All binaries we need, with full Nix store paths
  bash = "${pkgs.bash}/bin/bash";
  git = "${pkgs.git}/bin/git";
  curl = "${pkgs.curl}/bin/curl";
  mkpasswd = "${pkgs.mkpasswd}/bin/mkpasswd";
  nixos-rebuild = "/run/current-system/sw/bin/nixos-rebuild";
  systemctl = "${pkgs.systemd}/bin/systemctl";
  uname = "${pkgs.coreutils}/bin/uname";
  date = "${pkgs.coreutils}/bin/date";
  cat = "${pkgs.coreutils}/bin/cat";
  rm = "${pkgs.coreutils}/bin/rm";
  mkdir = "${pkgs.coreutils}/bin/mkdir";
  echo = "${pkgs.coreutils}/bin/echo";
  head = "${pkgs.coreutils}/bin/head";
  grep = "${pkgs.gnugrep}/bin/grep";
  python3 = "${pkgs.python3}/bin/python3";

  # The seed-pull script with all paths baked in
  seedPullScript = pkgs.writeShellScript "seed-pull.sh" ''
    # seed-pull.sh — Pulls a full OpenOS version from GitHub and rebuilds
    set -euo pipefail

    REPO_URL="''${1:?repo_url required}"
    CHANNEL="''${2:-stable}"
    HOSTNAME="''${3:-openos}"
    DOMAIN="''${4:-openos.local}"
    TIMEZONE="''${5:-UTC}"
    PASSWORD="''${6:?password required}"
    HEADSCALE_URL="''${7:-}"

    FLAKE_DIR="/etc/openos/flake"
    STATE_DIR="/var/lib/openos-seed"

    log() { ${echo} "[OpenOS] $*"; }

    # ── Step 1: Clone or update the repository ──
    if [ -d "$FLAKE_DIR/.git" ]; then
      log "Updating existing repository..."
      cd "$FLAKE_DIR"
      ${git} fetch --all --tags 2>&1
    else
      log "Cloning OpenOS repository..."
      ${rm} -rf "$FLAKE_DIR"
      ${git} clone "$REPO_URL" "$FLAKE_DIR" 2>&1
      cd "$FLAKE_DIR"
      ${git} fetch --all --tags 2>&1
    fi

    # ── Step 2: Select the version based on channel ──
    log "Selecting version for channel: $CHANNEL"

    case "$CHANNEL" in
      stable)
        TARGET_TAG=$(${git} tag -l 'v*' --sort=-v:refname | ${grep} -v '\-\(beta\|rc\|alpha\|dev\)' | ${head} -1 || true)
        if [ -z "$TARGET_TAG" ]; then
          log "No stable release found. Using main branch."
          TARGET_REF="origin/main"
        else
          TARGET_REF="$TARGET_TAG"
        fi
        ;;
      beta)
        TARGET_TAG=$(${git} tag -l 'v*' --sort=-v:refname | ${head} -1 || true)
        if [ -z "$TARGET_TAG" ]; then
          TARGET_REF="origin/main"
        else
          TARGET_REF="$TARGET_TAG"
        fi
        ;;
      nightly)
        TARGET_REF="origin/main"
        ;;
      *)
        log "Unknown channel: $CHANNEL. Falling back to main."
        TARGET_REF="origin/main"
        ;;
    esac

    log "Target version: $TARGET_REF"
    ${git} checkout "$TARGET_REF" 2>&1

    # ── Step 3: Write host configuration ──
    log "Writing host configuration..."

    ADMIN_HASH=$(${echo} "$PASSWORD" | ${mkpasswd} -m sha-512 -s 2>/dev/null || ${echo} "$PASSWORD")

    ${cat} > /etc/openos/host-config.nix << NIXEOF
    { config, pkgs, ... }:
    {
      networking.hostName = "$HOSTNAME";
      time.timeZone = "$TIMEZONE";
      openos.domain = "$DOMAIN";
      openos.adminEmail = "admin@$DOMAIN";

      users.users.admin = {
        isNormalUser = true;
        extraGroups = [ "wheel" "openos-data" "networkmanager" ];
        hashedPassword = "$ADMIN_HASH";
      };

      openos.updates = {
        enable = true;
        channel = "$CHANNEL";
        autoApply = false;
      };
    }
    NIXEOF

    # Write empty apps.nix if it doesn't exist
    if [ ! -f /etc/openos/apps.nix ]; then
      ${cat} > /etc/openos/apps.nix << 'NIXEOF'
    # Auto-generated by openos-api. Do not edit manually.
    {
    }
    NIXEOF
    fi

    # ── Step 4: Tailscale config ──
    if [ -n "$HEADSCALE_URL" ]; then
      log "Configuring Tailscale for $HEADSCALE_URL"
      ${cat} > /etc/openos/tailscale-config << EOF
    HEADSCALE_URL=$HEADSCALE_URL
    EOF
    fi

    # ── Step 5: Detect architecture and pick the right flake target ──
    ARCH=$(${uname} -m)
    case "$ARCH" in
      x86_64)  FLAKE_TARGET="openos" ;;
      aarch64) FLAKE_TARGET="openos-arm" ;;
      *)       log "WARNING: Unknown architecture $ARCH, trying x86_64"; FLAKE_TARGET="openos" ;;
    esac

    log "Building for architecture: $ARCH (target: $FLAKE_TARGET)"

    # ── Step 6: Build and switch to full system ──
    log "Building full OpenOS system... (this may take 10-30 minutes)"

    ${nixos-rebuild} switch \
      --flake "$FLAKE_DIR#$FLAKE_TARGET" \
      --option substituters "https://cache.nixos.org" \
      --option trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" \
      2>&1

    # ── Step 7: Mark transition complete ──
    VERSION="$TARGET_REF"
    if [[ "$VERSION" == origin/* ]]; then
      VERSION=$(${git} rev-parse --short HEAD)
    fi
    ${echo} "$VERSION" > /etc/openos/version
    ${echo} "full" > /etc/openos/mode

    log "Recording installation..."
    ${mkdir} -p "$STATE_DIR"
    ${cat} > "$STATE_DIR/install-info.json" << EOF
    {
      "installed_at": "$(${date} -Iseconds)",
      "version": "$VERSION",
      "channel": "$CHANNEL",
      "hostname": "$HOSTNAME",
      "domain": "$DOMAIN",
      "arch": "$ARCH",
      "repo": "$REPO_URL"
    }
    EOF

    log ""
    log "=== OpenOS installation complete ==="
    log "Version: $VERSION"
    log "The system will reboot into the full OpenOS server."
  '';

  # The seed panel Python script with paths baked in
  seedPanelScript = pkgs.writeText "seed-panel.py" ''
    #!/usr/bin/env python3
    """
    OpenOS Seed Panel — Setup Wizard
    """

    import http.server
    import json
    import os
    import subprocess
    import socket

    PORT = 80
    STATE_DIR = "/var/lib/openos-seed"
    REPO_URL = "https://github.com/fritte-MOOD/OpenOS-Server.git"
    BASH = "${bash}"
    SEED_PULL = "${seedPullScript}"

    os.makedirs(STATE_DIR, exist_ok=True)


    def get_ip():
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.connect(("8.8.8.8", 80))
            ip = s.getsockname()[0]
            s.close()
            return ip
        except Exception:
            return "unknown"


    def get_system_info():
        info = {}
        try:
            with open("/proc/meminfo") as f:
                for line in f:
                    if line.startswith("MemTotal:"):
                        kb = int(line.split()[1])
                        info["memory_gb"] = round(kb / 1024 / 1024, 1)
        except Exception:
            info["memory_gb"] = "?"

        try:
            result = subprocess.run(["lsblk", "-d", "-o", "NAME,SIZE,MODEL", "--json"],
                                    capture_output=True, text=True, timeout=5)
            data = json.loads(result.stdout)
            info["disks"] = data.get("blockdevices", [])
        except Exception:
            info["disks"] = []

        try:
            result = subprocess.run(["${uname}", "-m"], capture_output=True, text=True, timeout=5)
            info["arch"] = result.stdout.strip()
        except Exception:
            info["arch"] = "unknown"

        info["ip"] = get_ip()
        info["hostname"] = socket.gethostname()
        return info


    SETUP_HTML = """<!DOCTYPE html>
    <html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>OpenOS Setup</title>
    <style>
      * { margin: 0; padding: 0; box-sizing: border-box; }
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
             background: #0a0a0a; color: #e5e5e5; min-height: 100vh;
             display: flex; align-items: center; justify-content: center; }
      .container { max-width: 600px; width: 100%; padding: 2rem; }
      h1 { font-size: 1.8rem; margin-bottom: 0.5rem; color: #fff; }
      .subtitle { color: #888; margin-bottom: 2rem; }
      .info-box { background: #1a1a1a; border: 1px solid #333; border-radius: 8px;
                  padding: 1rem; margin-bottom: 1.5rem; }
      .info-row { display: flex; justify-content: space-between; padding: 0.3rem 0; }
      .info-label { color: #888; }
      .info-value { color: #fff; font-family: monospace; }
      .step { background: #1a1a1a; border: 1px solid #333; border-radius: 8px;
              padding: 1.5rem; margin-bottom: 1rem; }
      .step h2 { font-size: 1.1rem; margin-bottom: 1rem; color: #fff; }
      label { display: block; color: #aaa; font-size: 0.85rem; margin-bottom: 0.3rem; }
      input, select { width: 100%; padding: 0.6rem; background: #0a0a0a; border: 1px solid #444;
                      border-radius: 4px; color: #fff; font-size: 0.95rem; margin-bottom: 0.8rem; }
      input:focus, select:focus { outline: none; border-color: #f97316; }
      button { padding: 0.7rem 1.5rem; background: #f97316; color: #000; border: none;
               border-radius: 6px; font-size: 1rem; font-weight: 600; cursor: pointer;
               width: 100%; margin-bottom: 0.5rem; }
      button:hover { background: #fb923c; }
      button:disabled { background: #555; color: #888; cursor: not-allowed; }
      .btn-secondary { background: #333; color: #fff; }
      .btn-secondary:hover { background: #444; }
      .log { background: #000; border: 1px solid #333; border-radius: 4px;
             padding: 0.8rem; font-family: monospace; font-size: 0.8rem;
             max-height: 400px; overflow-y: auto; white-space: pre-wrap;
             color: #aaa; display: none; margin-top: 1rem; }
      .status { text-align: center; padding: 0.5rem; border-radius: 4px;
                margin-top: 0.5rem; font-size: 0.9rem; }
      .status.ok { background: #052e16; color: #22c55e; }
      .status.err { background: #2d0a0a; color: #ef4444; }
      .status.working { background: #1a1000; color: #f97316; }
      .terminal { display: none; margin-top: 1rem; }
      .terminal-output { background: #000; border: 1px solid #333; border-radius: 4px;
                         padding: 0.8rem; font-family: monospace; font-size: 0.85rem;
                         min-height: 150px; max-height: 300px; overflow-y: auto;
                         white-space: pre-wrap; color: #0f0; }
      .terminal-input { display: flex; gap: 0.5rem; margin-top: 0.5rem; }
      .terminal-input input { flex: 1; margin-bottom: 0; }
      .terminal-input button { width: auto; padding: 0.6rem 1rem; }
    </style>
    </head>
    <body>
    <div class="container">
      <h1>OpenOS Server Setup</h1>
      <p class="subtitle">Seed system is running. Configure your server below.</p>

      <div class="info-box">
        <div class="info-row"><span class="info-label">IP Address</span><span class="info-value" id="ip">...</span></div>
        <div class="info-row"><span class="info-label">Architecture</span><span class="info-value" id="arch">...</span></div>
        <div class="info-row"><span class="info-label">Memory</span><span class="info-value" id="memory">...</span></div>
      </div>

      <form id="setupForm">
        <div class="step" id="step1">
          <h2>1. Server Configuration</h2>
          <label>Hostname</label>
          <input name="hostname" value="openos" required>
          <label>Domain</label>
          <input name="domain" value="openos.local">
          <label>Timezone</label>
          <input name="timezone" value="Europe/Berlin">
          <label>Admin Password</label>
          <input name="password" type="password" required minlength="8">
        </div>

        <div class="step" id="step2">
          <h2>2. Network (Tailscale)</h2>
          <label>Headscale Server URL (optional)</label>
          <input name="headscale_url" placeholder="https://hs.example.com">
          <p style="color:#666;font-size:0.8rem;">Leave empty to configure later.</p>
        </div>

        <div class="step" id="step3">
          <h2>3. OpenOS Version</h2>
          <label>Repository</label>
          <input name="repo_url" value="https://github.com/fritte-MOOD/OpenOS-Server.git">
          <label>Channel</label>
          <select name="channel">
            <option value="stable">Stable (recommended)</option>
            <option value="beta">Beta (release candidates)</option>
            <option value="nightly" selected>Nightly (latest)</option>
          </select>
        </div>

        <button type="submit" id="installBtn">Install OpenOS</button>
        <button type="button" class="btn-secondary" onclick="toggleTerminal()">Open Terminal</button>
      </form>

      <div class="log" id="log"></div>
      <div class="status" id="status" style="display:none;"></div>

      <div class="terminal" id="terminal">
        <h2 style="color:#fff;margin-bottom:0.5rem;">Terminal</h2>
        <div class="terminal-output" id="termOutput">$ </div>
        <div class="terminal-input">
          <input type="text" id="termCmd" placeholder="Enter command..." onkeypress="if(event.key==='Enter')runCmd()">
          <button onclick="runCmd()">Run</button>
        </div>
      </div>
    </div>

    <script>
    fetch('/api/info').then(r=>r.json()).then(d=>{
      document.getElementById('ip').textContent=d.ip||'?';
      document.getElementById('arch').textContent=d.arch||'?';
      document.getElementById('memory').textContent=(d.memory_gb||'?')+' GB';
    });

    function toggleTerminal() {
      const t = document.getElementById('terminal');
      t.style.display = t.style.display === 'none' ? 'block' : 'none';
    }

    async function runCmd() {
      const input = document.getElementById('termCmd');
      const output = document.getElementById('termOutput');
      const cmd = input.value.trim();
      if (!cmd) return;
      input.value = '';
      output.textContent += cmd + '\\n';
      try {
        const res = await fetch('/api/exec', {
          method: 'POST',
          headers: {'Content-Type': 'application/json'},
          body: JSON.stringify({cmd: cmd})
        });
        const data = await res.json();
        if (data.stdout) output.textContent += data.stdout;
        if (data.stderr) output.textContent += data.stderr;
        output.textContent += '$ ';
        output.scrollTop = output.scrollHeight;
      } catch(e) {
        output.textContent += 'Error: ' + e.message + '\\n$ ';
      }
    }

    document.getElementById('setupForm').addEventListener('submit', async(e)=>{
      e.preventDefault();
      const btn=document.getElementById('installBtn');
      const log=document.getElementById('log');
      const status=document.getElementById('status');
      btn.disabled=true; btn.textContent='Installing...';
      log.style.display='block'; log.textContent='Starting installation...\\n';
      status.style.display='block'; status.className='status working';
      status.textContent='Installing... this may take 10-30 minutes.';

      const fd=new FormData(e.target);
      const data=Object.fromEntries(fd.entries());

      try {
        const res=await fetch('/api/install',{method:'POST',
          headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
        const reader=res.body.getReader();
        const decoder=new TextDecoder();
        while(true){
          const{done,value}=await reader.read();
          if(done)break;
          log.textContent+=decoder.decode(value);
          log.scrollTop=log.scrollHeight;
        }
        status.className='status ok';
        status.textContent='Installation complete! The server will reboot in 10 seconds.';
        btn.textContent='Done';
      } catch(err){
        status.className='status err';
        status.textContent='Installation failed: '+err.message;
        btn.disabled=false; btn.textContent='Retry';
      }
    });
    </script>
    </body>
    </html>"""


    class SeedHandler(http.server.BaseHTTPRequestHandler):
        def log_message(self, format, *args):
            pass

        def do_GET(self):
            if self.path == "/":
                self.send_response(200)
                self.send_header("Content-Type", "text/html")
                self.end_headers()
                self.wfile.write(SETUP_HTML.encode())

            elif self.path == "/api/info":
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps(get_system_info()).encode())

            elif self.path == "/api/status":
                mode = "seed"
                try:
                    with open("/etc/openos/mode") as f:
                        mode = f.read().strip()
                except Exception:
                    pass
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps({
                    "mode": mode,
                    "hostname": socket.gethostname(),
                    "ip": get_ip(),
                }).encode())

            else:
                self.send_error(404)

        def do_POST(self):
            if self.path == "/api/install":
                length = int(self.headers.get("Content-Length", 0))
                body = json.loads(self.rfile.read(length)) if length else {}

                self.send_response(200)
                self.send_header("Content-Type", "text/plain")
                self.send_header("Transfer-Encoding", "chunked")
                self.end_headers()

                def send_line(msg):
                    line = msg + "\n"
                    chunk = f"{len(line.encode()):x}\r\n{line}\r\n"
                    self.wfile.write(chunk.encode())
                    self.wfile.flush()

                try:
                    self._run_install(body, send_line)
                except Exception as e:
                    send_line(f"ERROR: {e}")

                self.wfile.write(b"0\r\n\r\n")
                self.wfile.flush()

            elif self.path == "/api/exec":
                length = int(self.headers.get("Content-Length", 0))
                body = json.loads(self.rfile.read(length)) if length else {}
                cmd = body.get("cmd", "")

                result = {"stdout": "", "stderr": "", "code": 0}
                try:
                    proc = subprocess.run(
                        [BASH, "-c", cmd],
                        capture_output=True, text=True, timeout=60,
                        cwd="/root",
                        env={**os.environ, "PATH": "/run/current-system/sw/bin:" + os.environ.get("PATH", "")}
                    )
                    result["stdout"] = proc.stdout
                    result["stderr"] = proc.stderr
                    result["code"] = proc.returncode
                except subprocess.TimeoutExpired:
                    result["stderr"] = "Command timed out (60s limit)\n"
                    result["code"] = -1
                except Exception as e:
                    result["stderr"] = f"Error: {e}\n"
                    result["code"] = -1

                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.end_headers()
                self.wfile.write(json.dumps(result).encode())

            else:
                self.send_error(404)

        def _run_install(self, config, send):
            hostname = config.get("hostname", "openos")
            domain = config.get("domain", "openos.local")
            timezone = config.get("timezone", "UTC")
            password = config.get("password", "")
            headscale_url = config.get("headscale_url", "")
            repo_url = config.get("repo_url", REPO_URL)
            channel = config.get("channel", "stable")

            send(f"=== OpenOS Installation ===")
            send(f"Hostname: {hostname}")
            send(f"Domain: {domain}")
            send(f"Channel: {channel}")
            send(f"Script: {SEED_PULL}")
            send("")

            send("Pulling OpenOS from GitHub...")
            try:
                proc = subprocess.run(
                    [BASH, SEED_PULL, repo_url, channel, hostname, domain, timezone, password, headscale_url],
                    capture_output=True, text=True, timeout=3600,
                    env={**os.environ, "PATH": "/run/current-system/sw/bin:" + os.environ.get("PATH", "")}
                )

                for line in proc.stdout.splitlines():
                    send(line)
                if proc.stderr:
                    for line in proc.stderr.splitlines():
                        send(f"[stderr] {line}")

                if proc.returncode == 0:
                    send("")
                    send("Installation complete!")
                    send("The server will reboot in 10 seconds...")
                    subprocess.Popen([BASH, "-c", "sleep 10 && ${systemctl} reboot -i || reboot -f"])
                else:
                    send(f"Installation failed with exit code {proc.returncode}")
            except Exception as e:
                send(f"ERROR: {e}")


    if __name__ == "__main__":
        print(f"OpenOS Seed Panel running on port {PORT}")
        print(f"Open http://{get_ip()}/ in your browser")
        server = http.server.HTTPServer(("0.0.0.0", PORT), SeedHandler)
        server.serve_forever()
  '';

in {
  networking.hostName = lib.mkDefault "openos-seed";

  openos = {
    domain = lib.mkDefault "openos.local";
    adminEmail = lib.mkDefault "admin@openos.local";
  };

  time.timeZone = lib.mkDefault "UTC";
  i18n.defaultLocale = "en_US.UTF-8";

  system.stateVersion = "24.11";

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };
  nixpkgs.config.allowUnfree = true;

  # ── Packages available in PATH ──
  environment.systemPackages = with pkgs; [
    vim git curl jq htop parted
    dosfstools e2fsprogs mkpasswd
    coreutils gnugrep gawk
  ];

  # ── SSH for remote access ──
  services.openssh = {
    enable = true;
    settings.PermitRootLogin = "yes";
  };

  # ── Root password for emergency console access ──
  users.users.root.initialPassword = "openos";

  # ── Seed admin panel ──
  systemd.services.openos-seed-panel = {
    description = "OpenOS Seed Setup Panel";
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];

    path = with pkgs; [ bash git coreutils gnugrep gawk util-linux ];

    serviceConfig = {
      Type = "simple";
      ExecStart = "${python3} ${seedPanelScript}";
      Restart = "always";
      RestartSec = 3;
      Environment = "PATH=/run/current-system/sw/bin:/run/wrappers/bin";
    };
  };

  # ── Firewall: allow HTTP for the setup wizard ──
  networking.firewall.allowedTCPPorts = [ 22 80 ];

  # ── Marker file so the API knows we're in seed mode ──
  environment.etc."openos/mode".text = "seed";
  environment.etc."openos/version".text = "seed-0.1.0";

  # ── Display IP address on console login ──
  services.getty.greetingLine = ''
    OpenOS Seed System
    
    Setup: Open http://$(hostname -I | awk '{print $1}')/ in your browser
    Emergency login: root / openos
    
    \l
  '';

  # ── Filesystem defaults ──
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };
  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };
  fileSystems."/data" = lib.mkDefault {
    device = "/dev/disk/by-label/data";
    fsType = "ext4";
    options = [ "defaults" "noatime" ];
  };

  # ── Bootloader ──
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "nodev";
    configurationLimit = 20;
  };
  boot.loader.efi.canTouchEfiVariables = false;
}
