# OpenOS Seed System
#
# Minimal "bootloader" installed from USB. Provides:
#   - GRUB boot menu with rollback
#   - Web-based setup wizard on port 80
#   - Pulls full OpenOS from GitHub
#
# Scripts: seed-pull.sh is generated by Nix (for correct store paths).
#          seed-panel.py is a plain file (to avoid Nix/JS/Python conflicts).
#          Paths are passed to Python via systemd environment variables.
{ config, lib, pkgs, ... }:
let
  # Generate seed-pull.sh with full Nix store paths baked in
  seedPullScript = pkgs.writeShellScript "seed-pull.sh" ''
    set -euo pipefail

    REPO_URL="''${1:?repo_url required}"
    CHANNEL="''${2:-stable}"
    HOSTNAME="''${3:-openos}"
    DOMAIN="''${4:-openos.local}"
    TIMEZONE="''${5:-UTC}"
    PASSWORD="''${6:?password required}"
    HEADSCALE_URL="''${7:-}"

    FLAKE_DIR="/etc/openos/flake"
    STATE_DIR="/var/lib/openos-seed"

    log() { echo "[OpenOS] $*"; }

    # ── Clone or update ──
    if [ -d "$FLAKE_DIR/.git" ]; then
      log "Updating existing repository..."
      cd "$FLAKE_DIR"
      ${pkgs.git}/bin/git fetch --all --tags 2>&1
    else
      log "Cloning OpenOS repository..."
      ${pkgs.coreutils}/bin/rm -rf "$FLAKE_DIR"
      ${pkgs.git}/bin/git clone "$REPO_URL" "$FLAKE_DIR" 2>&1
      cd "$FLAKE_DIR"
      ${pkgs.git}/bin/git fetch --all --tags 2>&1
    fi

    # ── Select version ──
    log "Selecting version for channel: $CHANNEL"

    case "$CHANNEL" in
      stable)
        TARGET_TAG=$(${pkgs.git}/bin/git tag -l 'v*' --sort=-v:refname | ${pkgs.gnugrep}/bin/grep -v '\-\(beta\|rc\|alpha\|dev\)' | ${pkgs.coreutils}/bin/head -1 || true)
        if [ -z "''${TARGET_TAG:-}" ]; then
          log "No stable release found. Using main branch."
          TARGET_REF="origin/main"
        else
          TARGET_REF="$TARGET_TAG"
        fi
        ;;
      beta)
        TARGET_TAG=$(${pkgs.git}/bin/git tag -l 'v*' --sort=-v:refname | ${pkgs.coreutils}/bin/head -1 || true)
        if [ -z "''${TARGET_TAG:-}" ]; then
          TARGET_REF="origin/main"
        else
          TARGET_REF="$TARGET_TAG"
        fi
        ;;
      nightly|*)
        TARGET_REF="origin/main"
        ;;
    esac

    log "Target version: $TARGET_REF"
    ${pkgs.git}/bin/git checkout "$TARGET_REF" 2>&1

    # ── Write host configuration ──
    log "Writing host configuration..."

    ADMIN_HASH=$(echo "$PASSWORD" | ${pkgs.mkpasswd}/bin/mkpasswd -m sha-512 -s 2>/dev/null || echo "$PASSWORD")

    cat > /etc/openos/host-config.nix << NIXEOF
    { config, pkgs, ... }:
    {
      networking.hostName = "$HOSTNAME";
      time.timeZone = "$TIMEZONE";
      openos.domain = "$DOMAIN";
      openos.adminEmail = "admin@$DOMAIN";
      users.users.admin = {
        isNormalUser = true;
        extraGroups = [ "wheel" "openos-data" "networkmanager" ];
        hashedPassword = "$ADMIN_HASH";
      };
      openos.updates = {
        enable = true;
        channel = "$CHANNEL";
        autoApply = false;
      };
    }
    NIXEOF

    if [ ! -f /etc/openos/apps.nix ]; then
      cat > /etc/openos/apps.nix << 'NIXEOF'
    {
    }
    NIXEOF
    fi

    # ── Tailscale ──
    if [ -n "$HEADSCALE_URL" ]; then
      log "Configuring Tailscale for $HEADSCALE_URL"
      echo "HEADSCALE_URL=$HEADSCALE_URL" > /etc/openos/tailscale-config
    fi

    # ── Detect arch ──
    ARCH=$(${pkgs.coreutils}/bin/uname -m)
    case "$ARCH" in
      x86_64)  FLAKE_TARGET="openos" ;;
      aarch64) FLAKE_TARGET="openos-arm" ;;
      *)       log "WARNING: Unknown arch $ARCH"; FLAKE_TARGET="openos" ;;
    esac

    log "Building for: $ARCH (target: $FLAKE_TARGET)"

    # ── Build and switch ──
    log "Building full OpenOS system... (this may take 10-30 minutes)"

    /run/current-system/sw/bin/nixos-rebuild switch \
      --flake "$FLAKE_DIR#$FLAKE_TARGET" \
      --option substituters "https://cache.nixos.org" \
      --option trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" \
      2>&1

    # ── Mark complete ──
    VERSION="$TARGET_REF"
    if [[ "$VERSION" == origin/* ]]; then
      VERSION=$(${pkgs.git}/bin/git rev-parse --short HEAD)
    fi
    echo "$VERSION" > /etc/openos/version
    echo "full" > /etc/openos/mode

    ${pkgs.coreutils}/bin/mkdir -p "$STATE_DIR"
    cat > "$STATE_DIR/install-info.json" << EOF
    {
      "installed_at": "$(${pkgs.coreutils}/bin/date -Iseconds)",
      "version": "$VERSION",
      "channel": "$CHANNEL",
      "hostname": "$HOSTNAME",
      "domain": "$DOMAIN",
      "arch": "$ARCH",
      "repo": "$REPO_URL"
    }
    EOF

    log ""
    log "=== OpenOS installation complete ==="
    log "Version: $VERSION"
  '';

in {
  networking.hostName = lib.mkDefault "openos-seed";

  openos = {
    domain = lib.mkDefault "openos.local";
    adminEmail = lib.mkDefault "admin@openos.local";
  };

  time.timeZone = lib.mkDefault "UTC";
  i18n.defaultLocale = "en_US.UTF-8";
  system.stateVersion = "24.11";

  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    auto-optimise-store = true;
  };
  nixpkgs.config.allowUnfree = true;

  environment.systemPackages = with pkgs; [
    vim git curl jq htop parted
    dosfstools e2fsprogs mkpasswd
    coreutils gnugrep gawk
  ];

  # ── SSH + root login for emergency ──
  services.openssh = {
    enable = true;
    settings.PermitRootLogin = "yes";
  };
  users.users.root.initialPassword = "openos";

  # ── Seed admin panel (Python, paths via env vars) ──
  systemd.services.openos-seed-panel = {
    description = "OpenOS Seed Setup Panel";
    after = [ "network-online.target" ];
    wants = [ "network-online.target" ];
    wantedBy = [ "multi-user.target" ];

    path = with pkgs; [ bash git coreutils gnugrep gawk util-linux mkpasswd ];

    environment = {
      OPENOS_BASH = "${pkgs.bash}/bin/bash";
      OPENOS_SEED_PULL = "${seedPullScript}";
      OPENOS_REPO_URL = "https://github.com/fritte-MOOD/OpenOS-Server.git";
      PATH = "/run/current-system/sw/bin:/run/wrappers/bin";
    };

    serviceConfig = {
      Type = "simple";
      ExecStart = "${pkgs.python3}/bin/python3 ${./seed-panel.py}";
      Restart = "always";
      RestartSec = 3;
    };
  };

  # ── Firewall ──
  networking.firewall.allowedTCPPorts = [ 22 80 ];

  # ── Seed markers ──
  environment.etc."openos/mode".text = "seed";
  environment.etc."openos/version".text = "seed-0.1.0";

  # ── Console greeting with IP ──
  services.getty.greetingLine = lib.mkForce ''
    \n
    OpenOS Seed System
    Setup: http://\\4/ in your browser
    Emergency login: root / openos
    \n
  '';

  # ── Filesystems ──
  fileSystems."/" = lib.mkDefault {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };
  fileSystems."/boot" = lib.mkDefault {
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = [ "fmask=0077" "dmask=0077" ];
  };
  fileSystems."/data" = lib.mkDefault {
    device = "/dev/disk/by-label/data";
    fsType = "ext4";
    options = [ "defaults" "noatime" ];
  };

  # ── Bootloader ──
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    device = "nodev";
    configurationLimit = 20;
  };
  boot.loader.efi.canTouchEfiVariables = false;
}
