#!/usr/bin/env bash
# seed-pull.sh — Pulls a full OpenOS version from GitHub and rebuilds
#
# Called by the seed panel after the user completes the setup wizard.
# This script transitions the system from "seed" mode to a full OpenOS server.
#
# Usage: seed-pull.sh <repo_url> <channel> <hostname> <domain> <timezone> <password> [headscale_url]
set -euo pipefail

REPO_URL="${1:?repo_url required}"
CHANNEL="${2:-stable}"
HOSTNAME="${3:-openos}"
DOMAIN="${4:-openos.local}"
TIMEZONE="${5:-UTC}"
PASSWORD="${6:?password required}"
HEADSCALE_URL="${7:-}"

FLAKE_DIR="/etc/openos/flake"
STATE_DIR="/var/lib/openos-seed"

log() { echo "[OpenOS] $*"; }

# ── Step 1: Clone or update the repository ──
if [ -d "$FLAKE_DIR/.git" ]; then
  log "Updating existing repository..."
  cd "$FLAKE_DIR"
  git fetch --all --tags 2>&1
else
  log "Cloning OpenOS repository..."
  rm -rf "$FLAKE_DIR"
  git clone "$REPO_URL" "$FLAKE_DIR" 2>&1
  cd "$FLAKE_DIR"
  git fetch --all --tags 2>&1
fi

# ── Step 2: Select the version based on channel ──
log "Selecting version for channel: $CHANNEL"

case "$CHANNEL" in
  stable)
    TARGET_TAG=$(git tag -l 'v*' --sort=-v:refname | grep -v '\-\(beta\|rc\|alpha\|dev\)' | head -1)
    if [ -z "$TARGET_TAG" ]; then
      log "No stable release found. Using main branch."
      TARGET_REF="origin/main"
    else
      TARGET_REF="$TARGET_TAG"
    fi
    ;;
  beta)
    TARGET_TAG=$(git tag -l 'v*' --sort=-v:refname | head -1)
    if [ -z "$TARGET_TAG" ]; then
      TARGET_REF="origin/main"
    else
      TARGET_REF="$TARGET_TAG"
    fi
    ;;
  nightly)
    TARGET_REF="origin/main"
    ;;
  *)
    log "Unknown channel: $CHANNEL. Falling back to main."
    TARGET_REF="origin/main"
    ;;
esac

log "Target version: $TARGET_REF"
git checkout "$TARGET_REF" 2>&1

# ── Step 3: Write host configuration ──
log "Writing host configuration..."

ADMIN_HASH=$(echo "$PASSWORD" | mkpasswd -m sha-512 -s 2>/dev/null || echo "$PASSWORD")

cat > /etc/openos/host-config.nix << NIXEOF
{ config, pkgs, ... }:
{
  networking.hostName = "$HOSTNAME";
  time.timeZone = "$TIMEZONE";
  openos.domain = "$DOMAIN";
  openos.adminEmail = "admin@$DOMAIN";

  users.users.admin = {
    isNormalUser = true;
    extraGroups = [ "wheel" "openos-data" "networkmanager" ];
    hashedPassword = "$ADMIN_HASH";
  };

  openos.updates = {
    enable = true;
    channel = "$CHANNEL";
    autoApply = false;
  };
}
NIXEOF

# Write empty apps.nix if it doesn't exist
if [ ! -f /etc/openos/apps.nix ]; then
  cat > /etc/openos/apps.nix << 'NIXEOF'
# Auto-generated by openos-api. Do not edit manually.
{
}
NIXEOF
fi

# ── Step 4: Tailscale config ──
if [ -n "$HEADSCALE_URL" ]; then
  log "Configuring Tailscale for $HEADSCALE_URL"
  cat > /etc/openos/tailscale-config << EOF
HEADSCALE_URL=$HEADSCALE_URL
EOF
fi

# ── Step 5: Detect architecture and pick the right flake target ──
ARCH=$(uname -m)
case "$ARCH" in
  x86_64)  FLAKE_TARGET="openos" ;;
  aarch64) FLAKE_TARGET="openos-arm" ;;
  *)       log "WARNING: Unknown architecture $ARCH, trying x86_64"; FLAKE_TARGET="openos" ;;
esac

log "Building for architecture: $ARCH (target: $FLAKE_TARGET)"

# ── Step 6: Build and switch to full system ──
log "Building full OpenOS system... (this may take 10-30 minutes)"

nixos-rebuild switch \
  --flake "$FLAKE_DIR#$FLAKE_TARGET" \
  --option substituters "https://cache.nixos.org" \
  --option trusted-public-keys "cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" \
  2>&1

# ── Step 7: Mark transition complete ──
VERSION="$TARGET_REF"
if [[ "$VERSION" == origin/* ]]; then
  VERSION=$(git rev-parse --short HEAD)
fi
echo "$VERSION" > /etc/openos/version
echo "full" > /etc/openos/mode

log "Recording installation..."
mkdir -p "$STATE_DIR"
cat > "$STATE_DIR/install-info.json" << EOF
{
  "installed_at": "$(date -Iseconds)",
  "version": "$VERSION",
  "channel": "$CHANNEL",
  "hostname": "$HOSTNAME",
  "domain": "$DOMAIN",
  "arch": "$ARCH",
  "repo": "$REPO_URL"
}
EOF

log ""
log "=== OpenOS installation complete ==="
log "Version: $VERSION"
log "The system will reboot into the full OpenOS server."
