package nixgen

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strings"
	"sync"
)

type Generator struct {
	appsNixPath string
	flakePath   string
	mu          sync.Mutex
}

func New(appsNixPath, flakePath string) *Generator {
	return &Generator{
		appsNixPath: appsNixPath,
		flakePath:   flakePath,
	}
}

type AppState struct {
	Enabled bool              `json:"enabled"`
	Config  map[string]string `json:"config,omitempty"`
}

func (g *Generator) ReadState() (map[string]AppState, error) {
	g.mu.Lock()
	defer g.mu.Unlock()

	data, err := os.ReadFile(g.appsNixPath + ".json")
	if err != nil {
		if os.IsNotExist(err) {
			return make(map[string]AppState), nil
		}
		return nil, fmt.Errorf("read state: %w", err)
	}

	var state map[string]AppState
	if err := json.Unmarshal(data, &state); err != nil {
		return nil, fmt.Errorf("parse state: %w", err)
	}
	return state, nil
}

func (g *Generator) EnableApp(appID string, config map[string]string) error {
	g.mu.Lock()
	defer g.mu.Unlock()

	state, err := g.readStateLocked()
	if err != nil {
		return err
	}

	state[appID] = AppState{Enabled: true, Config: config}
	return g.writeStateLocked(state)
}

func (g *Generator) DisableApp(appID string) error {
	g.mu.Lock()
	defer g.mu.Unlock()

	state, err := g.readStateLocked()
	if err != nil {
		return err
	}

	if s, ok := state[appID]; ok {
		s.Enabled = false
		state[appID] = s
	}
	return g.writeStateLocked(state)
}

func (g *Generator) IsEnabled(appID string) bool {
	state, err := g.ReadState()
	if err != nil {
		return false
	}
	s, ok := state[appID]
	return ok && s.Enabled
}

func (g *Generator) readStateLocked() (map[string]AppState, error) {
	data, err := os.ReadFile(g.appsNixPath + ".json")
	if err != nil {
		if os.IsNotExist(err) {
			return make(map[string]AppState), nil
		}
		return nil, err
	}

	var state map[string]AppState
	if err := json.Unmarshal(data, &state); err != nil {
		return nil, err
	}
	return state, nil
}

func (g *Generator) writeStateLocked(state map[string]AppState) error {
	// Write JSON state (source of truth for the Go daemon)
	jsonData, err := json.MarshalIndent(state, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal state: %w", err)
	}
	if err := os.WriteFile(g.appsNixPath+".json", jsonData, 0644); err != nil {
		return fmt.Errorf("write json state: %w", err)
	}

	// Generate the Nix file that NixOS imports
	nix := generateNix(state)
	if err := os.WriteFile(g.appsNixPath, []byte(nix), 0644); err != nil {
		return fmt.Errorf("write nix: %w", err)
	}

	return nil
}

func generateNix(state map[string]AppState) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by openos-api. Do not edit manually.\n")
	b.WriteString("{\n")

	keys := make([]string, 0, len(state))
	for k := range state {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, appID := range keys {
		s := state[appID]
		b.WriteString(fmt.Sprintf("  openos.apps.%s.enable = %v;\n", appID, s.Enabled))

		configKeys := make([]string, 0, len(s.Config))
		for k := range s.Config {
			configKeys = append(configKeys, k)
		}
		sort.Strings(configKeys)

		for _, ck := range configKeys {
			b.WriteString(fmt.Sprintf("  openos.apps.%s.%s = \"%s\";\n", appID, ck, s.Config[ck]))
		}
	}

	b.WriteString("}\n")
	return b.String()
}
